spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username_gmail>
    password: <api_key>
    properties.mail.smtp:
      ssl.trust: smtp.gmail.com
      auth: true
      starttls.enable: true